version: '3.9'

services:
  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:latest
    volumes:
      - "./data:/data"
    environment:
      # Replace this with your domain
      VIRTUAL_HOST: "sub.domain.com"
      VIRTUAL_PORT: 8008
      # Replace this with your domain
      LETSENCRYPT_HOST: "sub.domain.com"
      # Replace this with your domain
      SYNAPSE_SERVER_NAME: "sub.domain.com"
      SYNAPSE_REPORT_STATS: "yes"
    networks: ["matrix"]

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: synapse
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - "postgresdata:/var/lib/postgresql/"
    networks: ["matrix"]

networks:
  matrix:
    external: true

volumes:
  postgresdata:
# Generate the configuration file
# docker-compose run --rm synapse generate
# docker-compose up -d

# docker-compose down
# docker-compose up -d