version: '3.9'

services:
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy:latest
    volumes:
      - "certs:/etc/nginx/certs"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    networks: ["matrix"]
    restart: "always"
    ports:
      - 80:80
      - 443:443

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "certs:/etc/nginx/certs"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NGINX_PROXY_CONTAINER: "proxy"
    networks: ["matrix"]
    restart: "always"
    depends_on: ["proxy"]

networks:
  matrix:
    external: true

volumes:
  certs:
  vhost:
  html:
